#
# Makefile for the s3c framebuffer driver
#

obj-$(CONFIG_FB_S3C_EXT)		+= s3cfb.o
obj-$(CONFIG_FB_S3C_EXT)		+= s3cfb_spi.o
obj-$(CONFIG_PLAT_S3C64XX)		+= s3cfb_fimd4x.o
obj-$(CONFIG_PLAT_S5P64XX)		+= s3cfb_fimd5x.o
obj-$(CONFIG_PLAT_S5PC1XX)		+= s3cfb_fimd5x.o

obj-y		+= s3cfb_WXCAT35.o
obj-y		+= s3cfb_WXCAT43.o
obj-y		+= s3cfb_AT056.o
obj-y		+= s3cfb_AT070.o
obj-y		+= s3cfb_VGA800.o
obj-y		+= s3cfb_XGA1024.o
